# This is a basic workflow to help you get started with Actions

name: Time

on:
  push:
    branches: [ "main" ]

jobs:
  display_time:
    runs-on: ubuntu-latest

    steps:
    - name: What Time Is It
      run: date
